### ISSUE TITLE
Pop-up not being pressed on OnePlus 11: OOS14 - V1.3.4-g

### ISSUE THREAD

**Issue by Belgmeister** [Mygod/pogoplusle#36]
Hi there, 

The pairing pop-up is not being pressed for my although accessibility seems to be correctly enabled.
OnePlus 11 (CPH2449) - Oxygen OS 14.0
Pogo+LE version 1.3.4-g

- No battery restrictions for the app
- Notification monitor works as expected during Go+ session

Additional info that might be relevant:
on my old phone I noticed the pairing pop-up was appearing both on-screen and in the notification drawer, however on this new OnePlus 11 it does not appear in the notification drawer, on-screen notification only. Unable to find any setting where I can make it appear in the drawer as well.

Might be user error, but not sure how to determine.
Any help is appreciated, more info can be provided if needed.

**Comment by Mygod** [comment]
Android 14 changed how the pairing interaction worked, although this app continues to work on stock Android 14. Knowing OnePlus/Oppo, they probably have changed their implementation as well and deviated further from stock. To fix this, we will have to figure out the package name and the relevant labels on the new OS. Maybe can you start with a screenshot of the pairing notification/procedure?

**Comment by Belgmeister** [comment]
Thanks for the reply.

Made the screenshot as attached. 
Also included a screenshot of the system apps I could find under "accessibility". Will browse some more for possible relevant system packages.

I also made a video of the pairing process if relevant.

![Screenshot_2024-01-29-18-22-30-79_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/Mygod/pogoplusle/assets/64487458/524237ad-6b93-4b3f-88b1-c897badc068d)
![Screenshot_2024-01-29-18-15-05-89_41a74ddf68be21faad2fbbb691b15143](https://github.com/Mygod/pogoplusle/assets/64487458/03f15eaa-f2ca-4337-a06b-a204707a0e46)


P.s. for you compatibility table, you can include both Xiaomi Mi 10T Pro - MIUI 13 & Xiaomi 13T Pro - MIUI 14. Both worked like a charm.

**Comment by Mygod** [comment]
Thanks! That screenshot is helpful. I will see if I can find a ROM dump later. Do you still have an app with package name `com.oplus.wirelesssettings`?

**Comment by Belgmeister** [comment]
Doesn't seem like it!

**Comment by FynnleyNeko** [comment]
Should we keep this purely OnePlus related or should I go test my other not-so-stock Android 14 phones? Aka mostly Samsung/OneUI

**Comment by Mygod** [comment]
Thank you for your patience, please try this apk for your OnePlus/Oppo phones: https://github.com/Mygod/pogoplusle/releases/download/debug/pogoplusle-v1.3.4-debug.apk

I also have some reports that Samsung also caused some trouble for their Android 14 releases. If you can find any Samsung phone where the app breaks, that would be great.

**Comment by Belgmeister** [comment]
Thanks for the work!

Will ask around for the Samsung issue, can I forward the same APK for that?

I'm having trouble getting it to work as I'm unable to modify the settings needed. 
The app does not show up in the "special access" list as well. 

Am I missing something?

![Screenshot_2024-02-29-10-08-39-00_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/Mygod/pogoplusle/assets/64487458/e8f027d2-492a-47d3-b264-5455b25cd861)

![Screenshot_2024-02-29-10-12-00-99_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/Mygod/pogoplusle/assets/64487458/84ea7f55-9ff2-48aa-a932-6c57b923ccaf)

**Comment by Mygod** [comment]
https://support.google.com/android/answer/12623953?hl=en

**Comment by Mygod** [comment]
Great! Closing this for now. If you find any additional issues with Samsung phones, please open a new issue.
