### ISSUE TITLE
Auto device connection not working

### ISSUE THREAD

**Issue by Lansyyy** [Mygod/pogoplusle#39]
Bluetooth Device: Pokemon Go Plus +
Device Model: Google Pixel 6
App ver: 1.3.5-g
Configuration: Bluetooth Pairing Assistant ON, Monitor game notifications ON, Monitor Bluetooth ON

I have attempted to use the root mode, but it made no difference. No permissions denied.

**Comment by Mygod** [comment]
Pokemon GO Plus + should not have a popup every time you connect. What's not working?

**Comment by Lansyyy** [comment]
I'm referring to the on screen button. When clicked, it no longer auto
connects. See screenshot below.

It was functional for a while prior to the last Pokemon Go update.

**Comment by Mygod** [comment]
This app does not and will not affect the auto connect feature of Pokemon GO Plus + in any way.

**Comment by Lansyyy** [comment]
The app previously allowed me to skip the pairing dialogue and
automatically connected to my Bluetooth device from the in-game screen
button.

This is the main purpose of the app, no?

**Comment by Mygod** [comment]
As I said PGP+ does not have a recurring pairing dialog. Also your screenshot is not attached.

**Comment by Lansyyy** [comment]
That's not what I'm asking. I just want it to skip the pairing dialogue as
described in on the Play store. It's not functioning as normal.

I've reattached the screenshot showing my settings. Can you please assist
with this issue?
