### ISSUE TITLE
Notification not updating on Android 15

### ISSUE THREAD

**Issue by cr0w918** [Mygod/pogoplusle#42]
While the app is active and tracking go plus progress since Android 15 the notification does not update and stays at 0/0/0/0 when the disconnect happens It does show the correct data
![Screenshot_20241113-194217](https://github.com/user-attachments/assets/c7601db8-a778-4481-aae5-d32cf903d8f9)
![Screenshot_20241113-193419](https://github.com/user-attachments/assets/841b8598-37bc-4d98-83a9-8be364ba45f4)

**Comment by Mygod** [comment]
Did you update to latest version v1.3.8?

**Comment by cr0w918** [comment]
Yep, it's version 1.3.8-g
![Screenshot_20241114-012856](https://github.com/user-attachments/assets/b4303c7a-1386-4ed9-a6c7-1172eb321a78)

**Comment by Mygod** [comment]
Thanks. Did you turn on notification monitoring in the app? Send a screenshot of the app page please.

**Comment by cr0w918** [comment]
Yeah, since it worked before the android 15 update it's always been enabled.
![Screenshot_20241114-013404](https://github.com/user-attachments/assets/ee2368e0-04e5-474c-aaa1-e4cb51b80e31)

**Comment by shigutso** [comment]
I am having the same issue
Android 15 Pixel 8a
And also in my case I get the notification that my device is inactive, when it is working fine
Monitor Bluetooth option on or off does not fix the issue
![screenshot2](https://github.com/user-attachments/assets/5951e42e-67a1-44aa-a3b1-7473703ed35b)
![screenshot1](https://github.com/user-attachments/assets/6c3948e2-b7ce-4f7e-9339-015ab4a0cca7)

**Comment by shigutso** [comment]
Let me know how/if you need logs to help troubleshooting this on Android 15 thanks!

**Comment by Mygod** [comment]
This is the reason: https://www.reddit.com/r/androiddev/comments/1g7tdld/android_15_breaks_notification_listeners/

**Comment by cr0w918** [comment]
Hmm, I've tried disabling enhanced notifications from settings however, it still doesn't work as intended. At least we now know where the issue is.

**Comment by cr0w918** [comment]
Just wanted to let you know after disabling that setting since today it started working as intended again. Took a couple of days but maybe you can add the info to the app for other people on android 15. 
![Screenshot_20241204-142938](https://github.com/user-attachments/assets/9e43953e-05c5-40f5-9ec8-7efb90f0ef23)
