### ISSUE TITLE
Suggestion, Count the number of pokemon which were caught/failed to catch while the app is running

### ISSUE THREAD

**Issue by RecentRunner** [Mygod/pogoplusle#5]
Hello,

Would it be possible to add a counter inside the app which increments everytime the go plus catches/fails to catch a pokemon?

https://play.google.com/store/apps/details?id=com.sebas.gocompanion&hl=en_IE&gl=US

Go Companion used to have a similar feature but it hasn't been updated in a few years I would love to see this option added to this app, if it's outside of the scope of the project, that's fine too.

**Comment by Mygod** [comment]
No plan for it for now. Right now I am trying to find people to test (I assume it works for you) and get it on Play store. Yes I hate GO companion with a passion.

**Comment by Smultie** [comment]
The counter doesn't seem to add anything. I'm seeing 0 0 0 0

**Comment by Mygod** [comment]
@Smultie Make sure you enable "Monitor game notifications".

**Comment by Smultie** [comment]
Yes, it's working now! Thanks!

**Comment by RecentRunner** [comment]
Just wanted to say thank you for implementing the feature! I really do appreciate it ❤️
